### ISSUE TITLE
[Opinion] Don't waste your time and uninstall this hot mess.

### ISSUE THREAD

**Issue by LeadAssimilator** [microsoftfeedback/WinDbg-Feedback#136]
This thing is not even close to being ready for even lite developer user.  Every little thing causes immediate frustration coupled with 500% more typing and clicking.  Unless you like that sort of thing, it is time to switch back to the old windbg and leave this thing alone for another 3 years.

FYI: I used this when it was first available and it was in a much better state than it is today.  It is perplexing how it managed to get worse after many years; though that explains why it is still in preview.  And it seems like in preview it will forever remain unless something seriously changes.

**Comment by lzybkr** [comment]
There will always be people that prefer the classic version of WinDbg but they are in the minority. We don't have the resources to maintain both versions so over time the old version will stagnate. That might be exactly what some people want so maybe that's fine.

If you have constructive feedback that you'd like see addressed in the new version, please feel free to do so by opening new issues.

Note that I will delete this issue because it violates the GitHub Community Guidelines in that it does not contribute in a positive and constructive way: https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct
