### ISSUE TITLE
Cannot input backslash in command window (German keyboard layout)

### ISSUE THREAD

**Issue by bw-86** [microsoftfeedback/WinDbg-Feedback#219]
When I try to enter a backslash via AltGr+ß on my German keyboard layout, the focus jumps inside the text of the command window and marks an earlier command or its output. This is a useful feature and I would love to have it available.

In order to input a backslash into a command, I have to copy/paste it from somewhere else or switch to a different keyboard layout (English works, of course).

**Comment by jsschultz** [comment]
Thank you for your valuable feedback and bringing this bug to our attention. We are able to reproduce this issue and are working on a fix. Until the fix is released, you can disable this behavior by enabling the "Disable keyboard shortcut to jump by section in command window output" setting (see below):

Settings -> Command Window -> Disable keyboard shortcut to jump by section in command window output

![image](https://github.com/user-attachments/assets/343d82e2-2a5d-4b8b-bee6-fd37364a3348)

Once the fix is released, you may uncheck this setting, if you would like to use this feature for highlighting sections in the command window output pane : 

Highlight previous section : Ctrl + [ (Oem4)
Highlight next section : Ctrl + ] (Oem6)

**Comment by jsschultz** [comment]
Fix available in version 1.2410.11001.0
