### ISSUE TITLE
TTD-x64 can not record trace for x64 application

### ISSUE THREAD

**Issue by omarekik** [microsoftfeedback/WinDbg-Feedback#251]
In a Windows 11 x64, TTD-x64 is able to record trace for x86 application but can not record trace for x64 application. I was using a simple C++ console application with this code:
`#include <iostream>
#include <string>
int main(){
    std::string str {};
    while (str.find("quit") == str.npos) { std::cin >> str; }
    std::cout << "Hello World!\n";
}`
Attached are the executable for both platforms (x86 and x64) [ConsoleApplication.zip](https://github.com/user-attachments/files/18147337/ConsoleApplication.zip)
By launching a time travel debugging session of the x64 ConsoleApplication using either WinDbg or TTD-x64, I was getting the following error message:
![image](https://github.com/user-attachments/assets/a0aae772-c4b1-44a6-b3aa-6e51ade10edc)
and attached you find the log file ConsoleApplication701.out [ConsoleApplication701.txt](https://github.com/user-attachments/files/18147056/ConsoleApplication701.txt)
The error message is `Error: Injecting into guest process failed with exitcode: 4294967295 - 0xFFFFFFFF
 This may be an indication of a privileges problem or that the process is already under tracing control and needs to be restarted.` Even though, both TTD.exe and ConsoleApplication.exe have the same privileges as shown in the following screenshots:
![image](https://github.com/user-attachments/assets/fe05b065-66cd-47af-a9ef-013e32e813eb)
![image](https://github.com/user-attachments/assets/b563e896-adf8-4903-a82a-39bdf0906eae)
 I was running TTD.exe from a terminal as a local admin with `-launch` option, so TTD will be launching the console application. 
I find it weird that trace recording works for x86 but not for x64, could you please check?

**Comment by omarekik** [comment]
Even though, it was possible to debug the x86 console application but not the x64 one, but the issue is purely related to a security policy in the Sophos antivirus.

**Comment by TheJCAB** [comment]
Sorry I'm late to respond but you're absolutely correct. The key indicator is "Error: GetNtdllAPIAddresses() failed for NtSetContextThread". In order to do its thing, TTD needs to intercept certain OS entrypoints. In this case, as you can imagine, with TTD being at its core an emulator, functions like `SetContextThread` cannot be allowed to divert control away from the emulator :-).

Security software, like antivirus, and other intrusion protection software, tends to also want to intercept OS entrypoints in order to monitor suspicious activity, which can obviously interfere with TTD's need to do the same. If you temporarily disable the antivirus either for the application in question or system-wide (each antivirus is different), you should have no problem recording the application.

I don't know why, but it appears Sophos is not providing the same level of monitoring for 32-bit programs. That's why TTD is working there.

HTH
