### ISSUE TITLE
!load command does not accept quoted path 

### ISSUE THREAD

**Issue by baget** [microsoftfeedback/WinDbg-Feedback#26]
if using !load and provide it with quoted path, windbg unable to load library, if you remove the quotes it works. 

for example:
```
6: kd> !load "C:\Utils\WinDbgPlugins\MEX\x64\mex.dll"
The call to LoadLibrary(C:UtilsWinDbgPluginsMEXdmex.dll) failed, Win32 error 0n2
    "The system cannot find the file specified."
Please check your debugger configuration and/or network access.

6: kd> !load C:\Utils\WinDbgPlugins\MEX\x64\mex.dll
Mex External 3.0.0.7148 Loaded!
```

**Comment by aluhrs13** [comment]
If you put quotes you need to escape the slashes, so 
`!load "C:\\Utils\\WinDbgPlugins\\MEX\\x64\\mex.dll"`

I realize this is pretty inconvenient since Explorer's "Copy as path" includes quotes, but it's probably not something we can reasonably change without breaking a lot of expectations in automated environments since this behavior has been around for decades.

**Comment by baget** [comment]
why you need Escape characters in the file path?
why not handle both cases? 
```
!load "C:\\Utils\\WinDbgPlugins\\MEX\\x64\\mex.dll"
!load "C:\Utils\WinDbgPlugins\MEX\x64\mex.dll"

```

is the following a valid input? (notice the \b and \n usage)
`!load "c:\\Test\\a\b\\c\n\\d\\mex.dll"`

**Comment by TimMisiak** [comment]
If you don't want to use escape characters, either use @" or leave off the quotes entirely.

``` .load C:\test\winde.dll ```

or

``` .load @"C:\test\winde.dll" ```

**Comment by baget** [comment]
> If you don't want to use escape characters, either use @" or leave off the quotes entirely.
> 
> `.load C:\test\mex.dll`
> 
> or
> 
> `.load @"C:\test\mex.dll"`

that reasonable solution.
maybe just need to update the documentation of the command.
